name: Build & Tag

on:
  push:
    branches: [ master ]
    tags-ignore: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mise and uv (if not already)
        run: |
          if ! command -v mise &> /dev/null; then
            curl https://mise.run | sh
            export PATH="$HOME/.local/share/mise/bin:$PATH"
          fi
          export PATH="$HOME/.local/bin:$PATH"
          mise install uv

      - name: Setup Python via mise
        run: |
          export PATH="$HOME/.local/share/mise/bin:$PATH"
          mise install
          mise exec -- python --version
      
      - name: Create and activate venv via uv
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          mise exec -- uv venv
          mise exec -- uv pip install -r requirements.txt

      - name: Run tests
        run: |
          export PATH="$HOME/.local/share/mise/bin:$PATH"
          mise exec -- pytest tests/

      - name: Create build artifact
        run: |
          mkdir -p dist
          cp -r src/* dist/

      - name: Create zip file
        run: |
          cd dist
          zip -r ../build.zip .
          cd ..

      - name: Auto tag (patch version)
        id: tagger
        run: |
          VERSION=$(git tag | sort -V | tail -n 1 | awk -F. '{OFS="."; $3+=1; print $1,$2,$3}')
          git tag "$VERSION"
          git push origin "$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update changelog
        run: |
          echo "## ${{ steps.tagger.outputs.version }}" >> CHANGELOG.md
          git log -1 --pretty=format:"- %s" >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "update changelog for ${{ steps.tagger.outputs.version }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.version }}
          name: "Release ${{ steps.tagger.outputs.version }}"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.version }}
          files: build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
