name: Run Tests and Update Wiki

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term --cov-report=html:coverage_html --cov-report=markdown > coverage.md || true

      - name: Generate test summary
        run: |
          echo "# 🧪 Test Results" > wiki/TestResults.md
          echo "\n_Last updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')_\n" >> wiki/TestResults.md
          echo '```' >> wiki/TestResults.md
          tail -n 30 coverage.md >> wiki/TestResults.md
          echo '```' >> wiki/TestResults.md

      - name: Push to Wiki
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki_repo
          cp wiki/TestResults.md wiki_repo/
          cd wiki_repo
          git add TestResults.md
          git commit -m "chore: update test results [CI]" || echo "No changes to commit"
          git push
